#!/usr/bin/env bash
set -Eeuo pipefail

PROJECT_DIR="/opt/secnet-cspm-demo"
SCAN_ROOT="$PROJECT_DIR/scan-results"
OUTPUT_DIR="$PROJECT_DIR/output"
AI_OUTPUT="$PROJECT_DIR/data"
REGION="ap-southeast-1"
LIMIT=5
RUN_ID="$(date +%Y%m%d-%H%M%S)"
SCAN_DIR="$SCAN_ROOT/scan-$RUN_ID"
ARCHIVE_DIR="$SCAN_ROOT/dashboard-archive/$RUN_ID"
LOG_FILE="$PROJECT_DIR/dashboard.log"
DASH_PATTERN='^/root/.local/share/pipx/venvs/prowler/bin/python /root/.local/bin/prowler dashboard$'

cd "$PROJECT_DIR"

echo "======================================"
echo " SecNet CSPM - Automated Scan"
echo " Run ID: $RUN_ID"
echo "======================================"

source "$PROJECT_DIR/.venv-ai/bin/activate"

set -a
source "$PROJECT_DIR/.env"
set +a

mkdir -p "$SCAN_DIR" "$OUTPUT_DIR" "$AI_OUTPUT"

# 1. Run Prowler
echo "[1/5] Running Prowler scan..."
/root/.local/bin/prowler aws \
  --region "$REGION" \
  --output-formats json-ocsf csv html \
  --output-directory "$SCAN_DIR"

# 2. Locate CSV generated by this scan
echo "[2/5] Locating scan CSV..."
CSV_FILE="$(find "$SCAN_DIR" -maxdepth 1 -type f -name '*.csv' -print -quit)"

if [[ -z "$CSV_FILE" ]]; then
  echo "ERROR: No CSV file was generated."
  exit 1
fi

echo "CSV: $CSV_FILE"

# 3. Archive previous dashboard CSVs, then install current CSV
echo "[3/5] Updating Dashboard data..."
mkdir -p "$ARCHIVE_DIR"

shopt -s nullglob
OLD_CSVS=("$OUTPUT_DIR"/*.csv)
for old_csv in "${OLD_CSVS[@]}"; do
  if [[ "$old_csv" != "$OUTPUT_DIR/$(basename "$CSV_FILE")" ]]; then
    mv -v "$old_csv" "$ARCHIVE_DIR/"
  fi
done
shopt -u nullglob

cp -f "$CSV_FILE" "$OUTPUT_DIR/"

# 4. Analyze findings with Gemini
echo "[4/5] Analyzing FAIL findings with Gemini..."
if PYTHONPATH="$PROJECT_DIR" python \
  "$PROJECT_DIR/scripts/analyze_latest_failures.py" \
  --scan-dir "$SCAN_DIR" \
  --output-dir "$AI_OUTPUT" \
  --limit "$LIMIT"; then
  echo "Gemini analysis completed."
else
  echo "WARNING: Gemini analysis failed; Prowler scan data is still saved."
fi

# 5. Restart Dashboard safely
echo "[5/5] Restarting Prowler Dashboard..."

DASH_PIDS="$(pgrep -f "$DASH_PATTERN" || true)"

if [[ -n "$DASH_PIDS" ]]; then
  while IFS= read -r pid; do
    [[ -n "$pid" ]] && kill -TERM "$pid" || true
  done <<< "$DASH_PIDS"
fi

# Wait for port to be released
PORT_FREE=0
for i in {1..20}; do
  if ! ss -lntp 2>/dev/null | grep -q ':11666'; then
    PORT_FREE=1
    break
  fi
  sleep 1
done

if [[ "$PORT_FREE" -ne 1 ]]; then
  echo "ERROR: Port 11666 is still in use."
  echo "Inspect with: ss -lntp | grep 11666"
  exit 1
fi

: > "$LOG_FILE"
nohup /root/.local/bin/prowler dashboard >> "$LOG_FILE" 2>&1 &

# Wait for Dashboard to listen
DASH_READY=0
for i in {1..15}; do
  if ss -lntp 2>/dev/null | grep -q ':11666'; then
    DASH_READY=1
    break
  fi
  sleep 1
done

if [[ "$DASH_READY" -ne 1 ]]; then
  echo "ERROR: Dashboard did not start. Recent log:"
  tail -n 40 "$LOG_FILE"
  exit 1
fi

echo "Dashboard is listening on 127.0.0.1:11666"

echo "======================================"
echo "Scan completed."
echo "Scan directory: $SCAN_DIR"
echo "Dashboard CSV: $OUTPUT_DIR/$(basename "$CSV_FILE")"
echo "Archived CSVs: $ARCHIVE_DIR"
echo "AI output: $AI_OUTPUT/ai-analysis.json"
echo "Dashboard: http://127.0.0.1:11666"
echo "======================================"
